sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: yangtao
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5t5fPrebWTyju7q5WQfh
    access-key-secret: LfdKIkQnfyc1subQt306fKWWsJyAw5
    bucket-name: sky-itcast-yt
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 2
