sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: yangtao
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: <access_key_id1>
    access-key-secret: <access_key_secret2>
    bucket-name: sky-itcast-yt
